export const SyncDepositHandlerAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "_assetAmount", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "sharesAmount_", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositReferred",
    inputs: [
      { name: "_assetAmount", type: "uint256", internalType: "uint256" },
      { name: "_referrer", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "sharesAmount_", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAsset",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDepositorAllowlist",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMaxSharePriceStaleness",
    inputs: [],
    outputs: [{ name: "", type: "uint24", internalType: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "init",
    inputs: [{ name: "_asset", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDepositorAllowlist",
    inputs: [{ name: "_list", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxSharePriceStaleness",
    inputs: [{ name: "_maxStaleness", type: "uint24", internalType: "uint24" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AssetSet",
    inputs: [{ name: "asset", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposit",
    inputs: [
      { name: "depositor", type: "address", indexed: false, internalType: "address" },
      { name: "assetAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "sharesAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "referrer", type: "bytes32", indexed: false, internalType: "bytes32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DepositorAllowlistSet",
    inputs: [{ name: "list", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MaxSharePriceStalenessSet",
    inputs: [{ name: "maxStaleness", type: "uint24", indexed: false, internalType: "uint24" }],
    anonymous: false,
  },
  { type: "error", name: "ComponentHelpersMixin__OnlyAdminOrOwner__Unauthorized", inputs: [] },
  { type: "error", name: "ComponentHelpersMixin__OnlyShares__Unauthorized", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "StorageHelpersLib__VerifyErc7201Location__Mismatch", inputs: [] },
  { type: "error", name: "SyncDepositHandler__Deposit__ZeroAssets", inputs: [] },
  { type: "error", name: "SyncDepositHandler__Deposit__ZeroShares", inputs: [] },
  { type: "error", name: "SyncDepositHandler__ValidateDepositor__DepositorNotAllowed", inputs: [] },
  { type: "error", name: "SyncDepositHandler__ValidateSharePriceTimestamp__SharePriceStale", inputs: [] },
] as const;
