name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/reusable-verify.yaml
    secrets: inherit

  snapshot:
    name: Snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run build
        run: pnpm build
      - name: Create snapshot
        run: pnpx pkg-pr-new@0.0.60 publish --compact --comment=update --pnpm ./packages/*
