name: CI
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/reusable-verify.yaml
    secrets: inherit

  changesets:
    name: Changesets
    if: github.repository_owner == 'enzymefinance'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Manage changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: publish package(s)"
          title: "chore: publish package(s)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
